Fixing syntax errors
Signed-off-by: julianweisbord <julianweisbord@gmail.com>

diff --git a/assingment1/stats/stats b/assingment1/stats/stats
--- a/assingment1/stats/stats
+++ b/assingment1/stats/stats
@@ -1,24 +1,12 @@
 #!/bin/bash -e
 
-if [ "$#" -lt 2 ] || ["$#" -ge 4];
+if [ "$#" -lt 2 ] || [ "$#" -ge 4 ]
   then echo "Usage: stats {-rows|-cols} [file]" >&2
   #send to stderr
   exit
 fi
 
-rowCol=$2
-
-if [[${rowCol:0:1} == "c"]]
-  then #call statistics func
-
-elif [[${rowCol:0:1} == "r"]]
-  then calc_avg #call statistics func
-
-else
-  echo "Invalid commandline arguments." >&2
-  #send to stderr
-  exit
-fi
+rowCol=$1
 
 
 calc_avg(){
@@ -31,14 +19,15 @@ calc_avg(){
     count_num = wc $line
     firstHalf = expr $count_num / 2
 
-    if[[ $count_num % 2 -gt 0 ]]
-      then expr $firstHalf + 1
+    if [ $count_num % 2 -gt 0 ]
+      then expr $firstHalf +1 #try ((++$firstHalf))
     fi
 
     secondHalf = $count_num - $firstHalf
     $line | tr '\t' '\n' | sort -n | head -n $firstHalf > file1.txt | tail -n $secondHalf > file2.txt #
-    if[[ $count_num % 2 == 0 ]]
-      if [[tail -n 1 $file1 -gt head -n 1 $file2]]
+    if [ $count_num % 2 == 0 ]
+    then
+      if [ tail -n 1 $file1 -gt head -n 1 $file2 ]
       then
         median = tail -n 1 $file1
       else
@@ -52,14 +41,24 @@ calc_avg(){
 
     for char in $line; do
       sum = expr $char + $sum
-
+    done
     mean = expr $sum/$count
     printf "$mean"
 
-
-
-
-
   done < "${1:-/dev/stdin}"
 }
+
+
+if [[ ${rowCol:1:2} == 'r' ]]
+  then calc_avg #call statistics func
+# elif [[${rowCol:0:1} == "c"]]
+#   then #call statistics func
+else
+  echo "Invalid commandline arguments." >&2
+  #send to stderr
+  exit
+fi
+
+
+
 exit 0 #exit with no errors
